### ISSUE TITLE
Visualizations for Accuacy

### ISSUE THREAD

**Issue by cfunk1210** [darpa-sail-on/sail-on-client#100]
Visualize the accuracy from algorithms during runs

To compare accuracy between different conditions (eg. backbones)

To understand classwise accuracy vs novelty
- Like a violin chart with each class on the x and the novelty on the y.  That way we can see the distribution breakdown per class.

**Comment by as6520** [comment]
Done in https://github.com/darpa-sail-on/visualize_scores
