### ISSUE TITLE
Moving requirements to algorithms

### ISSUE THREAD

**Issue by as6520** [darpa-sail-on/sail-on-client#77]
Currently, the Pipfile in sail-on-client maintains dependencies for the algorithms along with its own dependencies. This causes issues when algorithms require conflicting dependencies. Additionally,  we are not required to ensure that all algorithms should have common dependencies. Should we break the Pipfile to Pipfile associated with algorithms and maintained by the algorithms? This would include adding/updating Pipfile in the algorithms and removing the dependencies that were coming from downstream projects.

**Comment by as6520** [comment]
@owl-uccs Would you be okay with this change?

**Comment by as6520** [comment]
prijatelj would you be okay with this change?

**Comment by prijatelj** [comment]
This sounds fine to me. So to ensure I understand: there is the pip file for the client, and then those deps that an algorithm relies on are excluded from the algorithm's own pip requirements file? Is that correct?

**Comment by as6520** [comment]
The pipfile for sail-on-client has requirements that are associated with algorithms and sail-on-client rather than just sail-on-client. This can cause problems if there are algorithms that have competitive requirements. So the requirements for the algorithms would be moved from sail-on-client to the algorithms. Additionally, we would add sail-on-client as a requirement in the algorithms too.
